syntax = "proto3";

import "configuration/Components/LevelDifficultyComponent.proto";
import "configuration/Components/TuningComponent.proto";
import "configuration/Components/ResourceComponent.proto";
import "configuration/Components/AssetComponent.proto";
import "configuration/Components/PlayerLevelCurveComponent.proto";
import "configuration/Components/FeatureComponent.proto";
import "configuration/Components/LootTableComponent.proto";
import "configuration/Components/WorldComponent.proto";
import "configuration/Components/UpgradableComponent.proto";
import "configuration/Components/CraftingRecipeComponent.proto";
import "configuration/Components/PurchasableComponent.proto";
import "configuration/Components/LocalizedNameComponent.proto";

message ComponentSet
{
	LevelDifficultyComponent level_difficulty = 1;
	TuningComponent tuning = 2;
	ResourceComponent resource = 3;
	AssetComponent asset = 4;
	PlayerLevelCurveComponent player_level_curve = 5;
	FeatureComponent feature = 6;
	LootTableComponent loot_table = 7;
	WorldComponent world = 8;
	UpgradableComponent upgradable = 9;
	CraftingRecipeComponent crafting_recipe = 10;
	PurchasableComponent purchasable = 11;
	LocalizedNameComponent localized_name = 12;
}